Greeting menu
lippertmark/Learn_En_words pull request #1
Opened 2022-04-03 11:22 UTC by ttalova

2022-04-05 21:02 UTC, lippertmark requested changes
прошу исправить, а так в целом ты молодец, мне понравилось 😻

2022-04-05 21:02 UTC, lippertmark commented on main.py
> -    user = sql_new_user()
лишняя строка, потому что 49 создает юзера, а это ты ее вызываешь без параметров и эта функция ничего не возвращает, так что не могу понять зачем ты присваиваешь это в переменную user

2022-04-05 21:02 UTC, lippertmark commented on main.py
>      sticker = open('welcome.webp', 'rb')
в целом ок, но картинку надо положить в отдельную папку img)

2022-04-06 14:40 UTC, ttalova commented on main.py
>      sticker = open('welcome.webp', 'rb')
сделано

2022-04-06 15:18 UTC, merged